spring.application.name=futbol
server.port=8080

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/examen_spring_dwes?serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=daw12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate - CAMBIADO EL DIALECTO

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
